#! /bin/bash

# This script deploys the OneStop application to the Tomcat server on the production machine. This
# script should be run from the deployment server by running the deploy_server_script on the deploy
# server, this makes deployment convenient. You can run this script by executing './deployment_script'.
# Right now the blackbox_testing branch is used, but this will change after the application is tested
# in production and the testing branch is merged with the master branch. This script is necessary,
# since even capistrano-windows-server could not be made to work. It seems as though Windows does
# not allow you to delete files that are being used by any process, hence the need to stop Tomcat
# before removing the onestp directory in Tomcat's appBase directory. You may get a 404 error if this
# is not done.

############################################ VARIABLES BEGIN ########################################
#
# OneStop root directory
ONESTOP_ROOT="/c/Documents\ and\ Settings/Administrator/My\ Documents/Rails_Projects/onestop"

# Current Git branch
GIT_BRANCH=blackbox_testing

# Tomcat's service name. Get the list of services by running 'net start'
TOMCAT_SERVICE="Apache Tomcat 6.0 Tomcat6"

# Tomcat's appBase directory
APP_BASE="/c/Program\ Files/Apache\ Software\ Foundation/Tomcat\ 6.0/webapps"
#
############################################ VARIABLES END ##########################################

# Go to the onestop directory and get the latest code
eval cd $ONESTOP_ROOT
git checkout $GIT_BRANCH
git pull origin $GIT_BRANCH

# Install any new gems
jruby -S bundle install

# Migrate any new tables or table structures
jruby -S rake db:migrate

# Precompile assets
jruby -S rake assets:precompile

# Create the warble file
jruby -S bundle exec warble

# Stop Tomcat
net stop "Apache Tomcat 6.0 Tomcat6"

# Remove the onestp directory and the onestop.war file in Tomcat's appBase directory
# This only works if you cd into $APP_BASE
eval cd $APP_BASE
rm -rf onestop
rm -rf onestop.war

# Move the warfile created above to Tomcat's appBase directory
eval cd $ONESTOP_ROOT
eval mv onestop.war $APP_BASE

# Start Tomcat
net start "Apache Tomcat 6.0 Tomcat6"
