source 'https://rubygems.org'

gem 'rails', :git => 'git://github.com/rails/rails.git', :branch => '3-2-stable'

gem 'activerecord-oracle_enhanced-adapter', :git => 'git://github.com/rsim/oracle-enhanced.git'

gem 'audited-activerecord', :git => 'git://github.com/collectiveidea/audited.git'
gem "friendly_id", "~> 4.0.1"
gem 'jruby-openssl'
gem 'json'
gem 'rabl'
gem 'strong_parameters'
gem 'activeadmin'
gem 'country-select'
gem 'useragent'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'coffee-script-source', '~> 1.4.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test, :performance do
  gem 'factory_girl_rails', "~> 4.0"
  gem 'faker'
  gem "json_spec", "~> 1.0.3"
  gem 'rspec-rails'
  gem 'ruby-debug'
  gem 'timecop'
end

group :development do
  gem "annotate", ">= 2.5.0"
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
end

group :test do
  gem "shoulda-matchers", "~> 1.5.4"
  gem 'spork-rails'
end

group :cucumber do
  gem 'headless'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'launchy'
end

group :production do
  gem 'warbler', ">= 1.3.7"
end
