EPCS:
  SUPERNPI:
    PROVIDER_ERROR_MESSAGE: Provider NPI is not found in Super NPI DB
    PROVIDER_NAME_ERROR_MESSAGE: Provider Name is not matching with Super NPI record
  DEA_NUMBER:
    CHECKSUM_ERROR_MESSAGE: Invalid DEA Number checksum is not correct