CREATE SEQUENCE "ONESTOP_ADMIN_USER_SEQ"

/

CREATE SEQUENCE "ONESTOP_AUDIT_SEQ"

/

CREATE SEQUENCE "ONESTOP_OIS_CLIENT_PREFERE_SEQ"

/

CREATE SEQUENCE "ONESTOP_OIS_CLIENT_SEQ"

/

CREATE SEQUENCE "ONESTOP_OIS_SEQ"

/

CREATE SEQUENCE "ONESTOP_OIS_USER_TOKEN_SEQ"

/

CREATE SEQUENCE "ONESTOP_ORGANIZATION_SEQ"

/

CREATE SEQUENCE "ONESTOP_PERFORMANCE_LOG_SEQ"

/

CREATE SEQUENCE "ONESTOP_USER_SEQ"

/

CREATE TABLE "ONESTOP_ADMIN_USER" (
"ID" VARCHAR2(36) NOT NULL,
 "EMAIL" VARCHAR2(100) DEFAULT ''  NOT NULL,
 "ENCRYPTED_PASSWORD" VARCHAR2(100) DEFAULT ''  NOT NULL,
 "RESET_PASSWORD_TOKEN" VARCHAR2(255),
 "RESET_PASSWORD_SENT_AT" TIMESTAMP(6),
 "REMEMBER_CREATED_AT" TIMESTAMP(6),
 "SIGN_IN_COUNT" NUMBER(38,0) DEFAULT 0,
 "CURRENT_SIGN_IN_AT" TIMESTAMP(6),
 "LAST_SIGN_IN_AT" TIMESTAMP(6),
 "CURRENT_SIGN_IN_IP" VARCHAR2(255),
 "LAST_SIGN_IN_IP" VARCHAR2(255),
 "CREATED_AT" DATE NOT NULL,
 "UPDATED_AT" DATE NOT NULL,
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "DISABLED" NUMBER(1,0) DEFAULT 0,
 "DISABLED_DATE" TIMESTAMP(6),
 "USER_NAME" VARCHAR2(120),
 CONSTRAINT SYS_C006992 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "I_ONESTOP_ADMIN_USER_EMAIL" ON "ONESTOP_ADMIN_USER" ("EMAIL")

/

CREATE UNIQUE INDEX "I_ONESTOP_ADMIN_USER_USER_NAME" ON "ONESTOP_ADMIN_USER" ("USER_NAME")

/

CREATE UNIQUE INDEX "I_ONE_ADM_USE_RES_PAS_TOK" ON "ONESTOP_ADMIN_USER" ("RESET_PASSWORD_TOKEN")

/



/

CREATE TABLE "ONESTOP_AUDIT" (
"ID" VARCHAR2(36) NOT NULL,
 "AUDITABLE_ID" VARCHAR2(36),
 "AUDITABLE_TYPE" VARCHAR2(255),
 "ASSOCIATED_ID" VARCHAR2(36),
 "ASSOCIATED_TYPE" VARCHAR2(255),
 "USER_ID" VARCHAR2(36),
 "USER_TYPE" VARCHAR2(255),
 "USERNAME" VARCHAR2(255),
 "ACTION" VARCHAR2(255),
 "AUDITED_CHANGES" CLOB,
 "VERSION" NUMBER(38,0) DEFAULT 0,
 "COMMENT" VARCHAR2(255),
 "REMOTE_ADDRESS" VARCHAR2(255),
 "CREATED_AT" TIMESTAMP(6),
 CONSTRAINT SYS_C006994 PRIMARY KEY (ID)
)

/

CREATE  INDEX "ASSOCIATED_INDEX" ON "ONESTOP_AUDIT" ("ASSOCIATED_ID", "ASSOCIATED_TYPE")

/

CREATE  INDEX "AUDITABLE_INDEX" ON "ONESTOP_AUDIT" ("AUDITABLE_ID", "AUDITABLE_TYPE")

/

CREATE  INDEX "I_ONESTOP_AUDIT_CREATED_AT" ON "ONESTOP_AUDIT" ("CREATED_AT")

/

CREATE  INDEX "USER_INDEX" ON "ONESTOP_AUDIT" ("USER_ID", "USER_TYPE")

/



/

CREATE TABLE "ONESTOP_OIS" (
"ID" VARCHAR2(36) NOT NULL,
 "OIS_NAME" VARCHAR2(80),
 "OIS_PASSWORD" VARCHAR2(80),
 "IP_ADDRESS_CONCAT" VARCHAR2(50),
 "OUTGOING_SERVICE_ID" VARCHAR2(80),
 "OUTGOING_SERVICE_PASSWORD" VARCHAR2(80),
 "ENROLLMENT_URL" VARCHAR2(1000),
 "AUTHENTICATION_URL" VARCHAR2(1000),
 "ORGANIZATION_ID" VARCHAR2(36),
 "DISABLED" NUMBER(1,0) DEFAULT 0,
 "SLUG" VARCHAR2(255) NOT NULL,
 "IDP_LEVEL" NUMBER(38,0),
 "DISABLED_DATE" TIMESTAMP(6),
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C006997 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "INDEX_ONESTOP_OIS_ON_SLUG" ON "ONESTOP_OIS" ("SLUG")

/



/

CREATE TABLE "ONESTOP_OISES_USERS" (
"OIS_ID" VARCHAR2(36),
 "USER_ID" VARCHAR2(36)
)

/

CREATE  INDEX "I_ONE_OIS_USE_OIS_ID_USE_ID" ON "ONESTOP_OISES_USERS" ("OIS_ID", "USER_ID")

/

CREATE  INDEX "I_ONE_OIS_USE_USE_ID_OIS_ID" ON "ONESTOP_OISES_USERS" ("USER_ID", "OIS_ID")

/



/

CREATE TABLE "ONESTOP_OIS_CLIENT" (
"ID" VARCHAR2(36) NOT NULL,
 "CLIENT_PASSWORD" VARCHAR2(80),
 "CLIENT_NAME" VARCHAR2(80),
 "IP_ADDRESS_CONCAT" VARCHAR2(50),
 "OIS_CLIENT_PREFERENCE_ID" VARCHAR2(36),
 "SLUG" VARCHAR2(255) NOT NULL,
 "DISABLED" NUMBER(1,0) DEFAULT 0,
 "DISABLED_DATE" TIMESTAMP(6),
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007000 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "I_ONESTOP_OIS_CLIENT_SLUG" ON "ONESTOP_OIS_CLIENT" ("SLUG")

/



/

CREATE TABLE "ONESTOP_OIS_CLIENT_PREFERENCE" (
"ID" VARCHAR2(36) NOT NULL,
 "CLIENT_NAME" VARCHAR2(80),
 "PREFERENCE_NAME" VARCHAR2(80),
 "FAQ_URL" VARCHAR2(1000),
 "HELP_URL" VARCHAR2(1000),
 "LOGO_URL" VARCHAR2(1000),
 "SLUG" VARCHAR2(255) NOT NULL,
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007003 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "I_ONE_OIS_CLI_PRE_SLU" ON "ONESTOP_OIS_CLIENT_PREFERENCE" ("SLUG")

/



/

CREATE TABLE "ONESTOP_OIS_USER_TOKEN" (
"ID" VARCHAR2(36) NOT NULL,
 "OIS_ID" VARCHAR2(36) NOT NULL,
 "USER_ID" VARCHAR2(36) NOT NULL,
 "TOKEN" VARCHAR2(255),
 "VERIFIED_TIMESTAMP" TIMESTAMP(6),
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007007 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "I_ONESTOP_OIS_USER_TOKEN_TOKEN" ON "ONESTOP_OIS_USER_TOKEN" ("TOKEN")

/

CREATE  INDEX "I_ONE_OIS_USE_TOK_OIS_ID" ON "ONESTOP_OIS_USER_TOKEN" ("OIS_ID")

/



/

CREATE TABLE "ONESTOP_ORGANIZATION" (
"ID" VARCHAR2(36) NOT NULL,
 "ORGANIZATION_NAME" VARCHAR2(150),
 "ADDRESS1" VARCHAR2(100),
 "ADDRESS2" VARCHAR2(100),
 "CITY" VARCHAR2(100),
 "STATE_CODE" VARCHAR2(2),
 "POSTAL_CODE" VARCHAR2(20),
 "COUNTRY_CODE" VARCHAR2(20) DEFAULT 'USA'  NOT NULL,
 "CONTACT_FIRST_NAME" VARCHAR2(120) NOT NULL,
 "CONTACT_LAST_NAME" VARCHAR2(120) NOT NULL,
 "CONTACT_PHONE" VARCHAR2(20),
 "CONTACT_FAX" VARCHAR2(20),
 "CONTACT_EMAIL" VARCHAR2(100),
 "ORGANIZATION_NPI" VARCHAR2(10),
 "DISABLED" NUMBER(1,0) DEFAULT 0,
 "DISABLED_DATE" TIMESTAMP(6),
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007012 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "I_ONE_ORG_ORG_NPI" ON "ONESTOP_ORGANIZATION" ("ORGANIZATION_NPI")

/



/

CREATE TABLE "ONESTOP_PERFORMANCE_LOG" (
"ID" VARCHAR2(36) NOT NULL,
 "CLIENT_ID" VARCHAR2(36),
 "REQUEST_IP" VARCHAR2(20),
 "REQUEST_CONTENT" VARCHAR2(255),
 "REQUEST_PARAMS" CLOB,
 "REQUEST_SIZE" NUMBER(38,0),
 "REQUEST_TIME" TIMESTAMP(6),
 "RESPONSE_CONTENT" CLOB,
 "RESPONSE_TIME" TIMESTAMP(6),
 "RESPONSE_SIZE" NUMBER(38,0),
 "CONTROLLER_NAME" VARCHAR2(255),
 "API_NAME" VARCHAR2(255),
 "SERVER_NAME" VARCHAR2(50),
 "SERVER_VERSION" VARCHAR2(50),
 "CLIENT_PLATFORM" VARCHAR2(50),
 "CLIENT_VERSION" VARCHAR2(50),
 "STATUS" VARCHAR2(255),
 "ERROR_TYPE" VARCHAR2(255),
 "ERROR_MESSAGE" VARCHAR2(2000),
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007014 PRIMARY KEY (ID)
)

/

CREATE  INDEX "I_ONE_PER_LOG_CLI_ID" ON "ONESTOP_PERFORMANCE_LOG" ("CLIENT_ID")

/



/

CREATE TABLE "ONESTOP_SCHEMA_MIGRATIONS" (
"VERSION" VARCHAR2(255) NOT NULL
)

/

CREATE UNIQUE INDEX "ONESTOP_UNIQUE_SCHEMA_MIGRATIO" ON "ONESTOP_SCHEMA_MIGRATIONS" ("VERSION")

/



/

CREATE TABLE "ONESTOP_USER" (
"ID" VARCHAR2(36) NOT NULL,
 "NPI" VARCHAR2(25) NOT NULL,
 "FIRST_NAME" VARCHAR2(80),
 "LAST_NAME" VARCHAR2(80),
 "ENABLED" NUMBER(1,0) DEFAULT 1,
 "CREATORID" VARCHAR2(36),
 "LASTUPDATEID" VARCHAR2(36),
 "CREATEDDATE" TIMESTAMP(6),
 "LASTUPDATEDATE" TIMESTAMP(6),
 "CREATEDDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(CREATEDDATE,'yyyymmddhh24miss'))) VIRTUAL,
 "LASTUPDATEDATE_AS_NUMBER" NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(LASTUPDATEDATE,'yyyymmddhh24miss'))) VIRTUAL,
 CONSTRAINT SYS_C007017 PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "INDEX_ONESTOP_USER_ON_NPI" ON "ONESTOP_USER" ("NPI")

/



/

ALTER TABLE "ONESTOP_OIS_CLIENT" ADD CONSTRAINT "ONE_OIS_CLI_OIS_CLI_PRE_ID_FK" FOREIGN KEY ("OIS_CLIENT_PREFERENCE_ID") REFERENCES "ONESTOP_ONESTOP_OIS_CLIENT_PREFERENCE"("ID")

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20121107165032')

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20121113211254')

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20121203164739')

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20121217195725')

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20130115203347')

/

INSERT INTO onestop_schema_migrations (version) VALUES ('20130118201257')

/

