# The following line sets the primary key type to a 36-character string
# using the OracleEnhanced adapter
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter::NATIVE_DATABASE_TYPES[:primary_key] = "VARCHAR2(36) NOT NULL PRIMARY KEY"

# The following block will assign the primary key to be a UUID before
# creation for all ActiveRecord objects.
ActiveRecord::Base.class_eval do
  self.sequence_name = 'autogenerated'

  before_create :set_primary_key

  private
  def set_primary_key
    self.id ||= SecureRandom.uuid
  end
end
