--------------------------------------------------------
--  File created - Wednesday-October-16-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence APP_FIELD_VALIDATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "APP_FIELD_VALIDATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence APP_UPLOAD_FIELDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "APP_UPLOAD_FIELDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence AUDIT_TRAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AUDIT_TRAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence CAOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CAOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence OIS_BATCH_UPLOADS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OIS_BATCH_UPLOADS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence ORGANIZATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ORGANIZATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROFILES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROFILES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROVIDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROVIDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROVIDER_APP_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROVIDER_APP_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROVIDER_DEA_NUMBERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROVIDER_DEA_NUMBERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROVIDER_ERROR_LOGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROVIDER_ERROR_LOGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence PROVI_ORGANIZATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROVI_ORGANIZATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence REGISTERED_APPS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REGISTERED_APPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Sequence ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
--------------------------------------------------------
--  DDL for Table APP_UPLOAD_FIELDS
--------------------------------------------------------

  CREATE TABLE "APP_UPLOAD_FIELDS" ("SYS_APP_UPLOAD_FIELD_ID" VARCHAR2(50 CHAR), "APP_UPLOAD_FIELD_ID" VARCHAR2(50 CHAR), "FK_REGISTERED_APP_ID" VARCHAR2(255 CHAR), "NAME" VARCHAR2(255 CHAR), "FIELD_TYPE" VARCHAR2(255 CHAR), "REQUIRED" NUMBER(1,0) DEFAULT 0, "DISPLAY_NAME" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table APP_UPLOAD_FIELD_VALIDATIONS
--------------------------------------------------------

  CREATE TABLE "APP_UPLOAD_FIELD_VALIDATIONS" ("SYS_APP_FIELD_VALIDATION_ID" VARCHAR2(50 CHAR), "APP_FIELD_VALIDATION_ID" VARCHAR2(50 CHAR), "FK_APP_UPLOAD_FIELD_ID" VARCHAR2(255 CHAR), "VALIDATION" VARCHAR2(255 CHAR), "ERROR_MESSAGE" CLOB, "FIELD_FORMAT" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table AUDIT_TRAILS
--------------------------------------------------------

  CREATE TABLE "AUDIT_TRAILS" ("SYS_AUDIT_TRAIL_ID" VARCHAR2(50 CHAR), "AUDIT_TRAIL_ID" VARCHAR2(50 CHAR), "FILE_NAME" VARCHAR2(255 CHAR), "FK_REGISTERED_APP_ID" VARCHAR2(255 CHAR), "TOTAL_PROVIDERS" VARCHAR2(255 CHAR), "FILE_URL" VARCHAR2(255 CHAR), "CREATED_DATE" DATE, "STATUS" VARCHAR2(255 CHAR), "FK_CAO_ID" VARCHAR2(255 CHAR), "FK_ORGANIZATION_ID" VARCHAR2(255 CHAR), "UPLOAD_STATUS" NUMBER(1,0) DEFAULT 0, "TOTAL_NPI_PROCESSED" NUMBER(38,0), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table CAOS
--------------------------------------------------------

  CREATE TABLE "CAOS" ("SYS_CAO_ID" VARCHAR2(50 CHAR), "CAO_ID" VARCHAR2(50 CHAR), "USER_ID" VARCHAR2(255 CHAR), "FIRST_NAME" VARCHAR2(255 CHAR), "LAST_NAME" VARCHAR2(255 CHAR), "IS_ACTIVE" NUMBER(1,0), "FK_ORGANIZATION_ID" VARCHAR2(255 CHAR), "FK_PROFILE_ID" VARCHAR2(255 CHAR), "EMAIL" VARCHAR2(255 CHAR) DEFAULT '', "ENCRYPTED_PASSWORD" VARCHAR2(255 CHAR) DEFAULT '', "RESET_PASSWORD_TOKEN" VARCHAR2(255 CHAR), "RESET_PASSWORD_SENT_AT" DATE, "REMEMBER_CREATED_AT" DATE, "SIGN_IN_COUNT" NUMBER(38,0) DEFAULT 0, "CURRENT_SIGN_IN_AT" DATE, "LAST_SIGN_IN_AT" DATE, "CURRENT_SIGN_IN_IP" VARCHAR2(255 CHAR), "LAST_SIGN_IN_IP" VARCHAR2(255 CHAR), "USERNAME" VARCHAR2(255 CHAR), "FK_ROLE_ID" VARCHAR2(255 CHAR), "DELETED_AT" DATE, "DELETED_REASON" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table OIS_BATCH_UPLOADS
--------------------------------------------------------

  CREATE TABLE "OIS_BATCH_UPLOADS" ("SYS_OIS_BATCH_UPLOAD_ID" VARCHAR2(50 CHAR), "OIS_BATCH_UPLOAD_ID" VARCHAR2(50 CHAR), "OIS_NAME" VARCHAR2(255 CHAR), "OIS_ID" VARCHAR2(255 CHAR), "OIS_PASSWORD" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table ORGANIZATIONS
--------------------------------------------------------

  CREATE TABLE "ORGANIZATIONS" ("SYS_ORGANIZATION_ID" VARCHAR2(50 CHAR), "ORGANIZATION_ID" VARCHAR2(50 CHAR), "NAME" VARCHAR2(255 CHAR), "ADDRESS1" VARCHAR2(100 CHAR), "ADDRESS2" VARCHAR2(100 CHAR), "CITY" VARCHAR2(100 CHAR), "STATE_CODE" VARCHAR2(255 CHAR), "POSTAL_CODE" VARCHAR2(20 CHAR), "COUNTRY_CODE" VARCHAR2(20 CHAR), "CONTACT_FIRST_NAME" VARCHAR2(120 CHAR), "CONTACT_LAST_NAME" VARCHAR2(120 CHAR), "CONTACT_PHONE" VARCHAR2(20 CHAR), "CONTACT_FAX" VARCHAR2(20 CHAR), "CONTACT_EMAIL" VARCHAR2(100 CHAR), "DELETED_AT" DATE, "DELETED_REASON" VARCHAR2(255 CHAR), "IDP_VENDOR_ID" VARCHAR2(255 CHAR), "ZIP_CODE" VARCHAR2(255 CHAR), "VENDOR_LABEL" VARCHAR2(255 CHAR), "VENDOR_NODE_LABEL" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table PROFILES
--------------------------------------------------------

  CREATE TABLE "PROFILES" ("SYS_PROFILE_ID" VARCHAR2(50 CHAR), "PROFILE_ID" VARCHAR2(50 CHAR), "PROFILE_NAME" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table PROVIDERS
--------------------------------------------------------

  CREATE TABLE "PROVIDERS" ("SYS_PROVIDER_ID" VARCHAR2(50 CHAR), "PROVIDER_ID" VARCHAR2(50 CHAR), "USERNAME" VARCHAR2(255 CHAR), "PASSWORD" VARCHAR2(255 CHAR), "ROLE" VARCHAR2(255 CHAR), "PREFIX" VARCHAR2(255 CHAR), "FIRST_NAME" VARCHAR2(255 CHAR), "MIDDLE_NAME" VARCHAR2(255 CHAR), "LAST_NAME" VARCHAR2(255 CHAR), "SUFFIX" VARCHAR2(255 CHAR), "DEGREES" CLOB, "NPI" VARCHAR2(255 CHAR), "BIRTH_DATE" DATE, "EMAIL" VARCHAR2(255 CHAR), "ADDRESS_1" CLOB, "ADDRESS_2" CLOB, "CITY" VARCHAR2(255 CHAR), "STATE" VARCHAR2(255 CHAR), "POSTAL_CODE" VARCHAR2(255 CHAR), "PHONE" VARCHAR2(255 CHAR), "FAX" VARCHAR2(255 CHAR), "DEPARTMENT" VARCHAR2(255 CHAR), "PROVIDER_OTP_TOKEN_SERIAL" VARCHAR2(35 CHAR), "RESEND_FLAG" VARCHAR2(1 CHAR) DEFAULT 'n', "HOSPITAL_ADMIN_FIRST_NAME" VARCHAR2(50 CHAR), "HOSPITAL_ADMIN_LAST_NAME" VARCHAR2(50 CHAR), "IDP_PERFORMED_DATE" DATE, "IDP_PERFORMED_TIME" TIMESTAMP (6), "HOSPITAL_IDP_TRANSACTION_ID" VARCHAR2(35 CHAR), "FK_PROVIDER_APP_DETAIL_ID" VARCHAR2(255 CHAR), "ZIP" VARCHAR2(10 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table PROVIDER_APP_DETAILS
--------------------------------------------------------

  CREATE TABLE "PROVIDER_APP_DETAILS" ("SYS_PROVIDER_APP_DETAIL_ID" VARCHAR2(50 CHAR), "PROVIDER_APP_DETAIL_ID" VARCHAR2(50 CHAR), "STATUS_CODE" VARCHAR2(255 CHAR), "STATUS_TEXT" CLOB, "FK_CAO_ID" VARCHAR2(255 CHAR), "FK_REGISTERED_APP_ID" VARCHAR2(255 CHAR), "FK_AUDIT_TRAIL_ID" VARCHAR2(255 CHAR), "FK_ORGANIZATION_ID" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table PROVIDER_DEA_NUMBERS
--------------------------------------------------------

  CREATE TABLE "PROVIDER_DEA_NUMBERS" ("SYS_PROVIDER_DEA_NUMBER_ID" VARCHAR2(50 CHAR), "PROVIDER_DEA_NUMBER_ID" VARCHAR2(50 CHAR), "PROVIDER_DEA" VARCHAR2(50 CHAR), "PROVIDER_DEA_STATE" VARCHAR2(15 CHAR), "PROVIDER_DEA_EXPIRATION_DATE" DATE, "FK_PROVIDER_APP_DETAIL_ID" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table PROVIDER_ERROR_LOGS
--------------------------------------------------------

  CREATE TABLE "PROVIDER_ERROR_LOGS" ("SYS_PROVIDER_ERROR_LOG_ID" VARCHAR2(50 CHAR), "PROVIDER_ERROR_LOG_ID" VARCHAR2(50 CHAR), "FK_PROVIDER_ID" VARCHAR2(255 CHAR), "APPLICATION_NAME" VARCHAR2(255 CHAR), "ERROR_MESSAGE" CLOB, "FK_CAO_ID" VARCHAR2(255 CHAR), "FK_AUDIT_TRAIL_ID" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table REGISTERED_APPS
--------------------------------------------------------

  CREATE TABLE "REGISTERED_APPS" ("SYS_REGISTERED_APP_ID" VARCHAR2(50 CHAR), "REGISTERED_APP_ID" VARCHAR2(50 CHAR), "APP_NAME" VARCHAR2(255 CHAR), "APP_OIS_URL" VARCHAR2(255 CHAR), "DATA_TEMPLATE" CLOB, "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROLES" ("SYS_ROLE_ID" VARCHAR2(50 CHAR), "ROLE_ID" VARCHAR2(50 CHAR), "NAME" VARCHAR2(255 CHAR), "DELETED" VARCHAR2(1) DEFAULT 'n', "CREATORID" VARCHAR2(30), "CREATEDDATE" DATE, "LASTUPDATEID" VARCHAR2(30), "LASTUPDATEDATE" DATE, "CREATEDDATE_AS_NUMBER" NUMBER(18,0), "LASTUPDATEDATE_AS_NUMBER" NUMBER(18,0))
/
--------------------------------------------------------
--  DDL for Table SCHEMA_MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "SCHEMA_MIGRATIONS" ("VERSION" VARCHAR2(255 CHAR))
/
REM INSERTING into AUDIT_TRAILS
SET DEFINE OFF;
REM INSERTING into CAOS
SET DEFINE OFF;
Insert into CAOS (SYS_CAO_ID,CAO_ID,USER_ID,FIRST_NAME,LAST_NAME,IS_ACTIVE,FK_ORGANIZATION_ID,FK_PROFILE_ID,EMAIL,ENCRYPTED_PASSWORD,RESET_PASSWORD_TOKEN,RESET_PASSWORD_SENT_AT,REMEMBER_CREATED_AT,SIGN_IN_COUNT,CURRENT_SIGN_IN_AT,LAST_SIGN_IN_AT,CURRENT_SIGN_IN_IP,LAST_SIGN_IN_IP,USERNAME,FK_ROLE_ID,DELETED_AT,DELETED_REASON,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('878bb1ea-d079-4325-aea9-41bbadfc431b','E8CA5B5CF597CBAAE040EC0A58997C21',null,null,null,null,null,null,'superadmin@onestop.com','$2a$10$xyRlMKYU0xzVDAvmQR/1D.JVmwRnPCLyqi7u.43rY.6Tt2VwL5N7e',null,null,null,2,to_date('15-10-13','DD-MM-RR'),to_date('15-10-13','DD-MM-RR'),'127.0.0.1','127.0.0.1','superadmin','7b4688bd-4883-4ec7-a024-e54d2fc97381',null,null,'n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('16-10-13','DD-MM-RR'),20131015153716,20131016063343);
Insert into CAOS (SYS_CAO_ID,CAO_ID,USER_ID,FIRST_NAME,LAST_NAME,IS_ACTIVE,FK_ORGANIZATION_ID,FK_PROFILE_ID,EMAIL,ENCRYPTED_PASSWORD,RESET_PASSWORD_TOKEN,RESET_PASSWORD_SENT_AT,REMEMBER_CREATED_AT,SIGN_IN_COUNT,CURRENT_SIGN_IN_AT,LAST_SIGN_IN_AT,CURRENT_SIGN_IN_IP,LAST_SIGN_IN_IP,USERNAME,FK_ROLE_ID,DELETED_AT,DELETED_REASON,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('40a8c1d6-fb4c-4e31-95d3-36aaa528826f','E8CA8B419B394455E040EC0A589903DE','#ABC1','Sarah','Parker',null,'5745e3b9-d6e3-461e-b488-37c9775a2585','346c882f-b8a8-42ba-8305-5d6acf274f02','sarah@parker.com','$2a$10$nHywTTbw4afPcN.v/YwNN.7nO57ueJiJZ3MGlYpH3lWqUHo4t.u12',null,null,null,5,to_date('16-10-13','DD-MM-RR'),to_date('16-10-13','DD-MM-RR'),'127.0.0.1','127.0.0.1','sarah','97b67f71-14af-4348-b4e7-10766b48fc82',null,null,'n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('16-10-13','DD-MM-RR'),20131015155138,20131016084752);
REM INSERTING into OIS_BATCH_UPLOADS
SET DEFINE OFF;
REM INSERTING into ORGANIZATIONS
SET DEFINE OFF;
Insert into ORGANIZATIONS (SYS_ORGANIZATION_ID,ORGANIZATION_ID,NAME,ADDRESS1,ADDRESS2,CITY,STATE_CODE,POSTAL_CODE,COUNTRY_CODE,CONTACT_FIRST_NAME,CONTACT_LAST_NAME,CONTACT_PHONE,CONTACT_FAX,CONTACT_EMAIL,DELETED_AT,DELETED_REASON,IDP_VENDOR_ID,ZIP_CODE,VENDOR_LABEL,VENDOR_NODE_LABEL,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('5745e3b9-d6e3-461e-b488-37c9775a2585','E8CA8B419B384455E040EC0A589903DE','Lenox Hill Hospital','Upper East Side','Manhattan','New York City','New York','10010','1','Albert','Rivers','667-677-9090',null,'rivers@ny.com',null,null,'8677223','10010','Meditech','MeditechNode','n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015155029,20131015155029);
REM INSERTING into PROFILES
SET DEFINE OFF;
Insert into PROFILES (SYS_PROFILE_ID,PROFILE_ID,PROFILE_NAME,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('346c882f-b8a8-42ba-8305-5d6acf274f02','E8CA5B5CF598CBAAE040EC0A58997C21','Doctor','n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153721,20131015153721);
Insert into PROFILES (SYS_PROFILE_ID,PROFILE_ID,PROFILE_NAME,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('46aab349-8cd7-44de-964a-663793f845c1','E8CA5B5CF599CBAAE040EC0A58997C21','Nurse','n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153721,20131015153721);
REM INSERTING into PROVIDERS
SET DEFINE OFF;
REM INSERTING into PROVIDER_APP_DETAILS
SET DEFINE OFF;
REM INSERTING into PROVIDER_DEA_NUMBERS
SET DEFINE OFF;
REM INSERTING into PROVIDER_ERROR_LOGS
SET DEFINE OFF;
REM INSERTING into REGISTERED_APPS
SET DEFINE OFF;
Insert into REGISTERED_APPS (SYS_REGISTERED_APP_ID,REGISTERED_APP_ID,APP_NAME,APP_OIS_URL,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('3cbc8d8c-4031-4a0a-a5c9-0b478a3d1746','E8CA5B5CF59ACBAAE040EC0A58997C21','EPCS-IDP',null,'n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153727,20131015153727);
Insert into REGISTERED_APPS (SYS_REGISTERED_APP_ID,REGISTERED_APP_ID,APP_NAME,APP_OIS_URL,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('a77393b1-c449-4bb5-8a95-c07ebe9764e1','E8CA5B5CF59BCBAAE040EC0A58997C21','Backline',null,'n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153727,20131015153727);
REM INSERTING into ROLES
SET DEFINE OFF;
Insert into ROLES (SYS_ROLE_ID,ROLE_ID,NAME,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('7b4688bd-4883-4ec7-a024-e54d2fc97381','E8CA5B5CF595CBAAE040EC0A58997C21','Admin','n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153705,20131015153705);
Insert into ROLES (SYS_ROLE_ID,ROLE_ID,NAME,DELETED,CREATORID,CREATEDDATE,LASTUPDATEID,LASTUPDATEDATE,CREATEDDATE_AS_NUMBER,LASTUPDATEDATE_AS_NUMBER) values ('97b67f71-14af-4348-b4e7-10766b48fc82','E8CA5B5CF596CBAAE040EC0A58997C21','COA','n','PROVISIONING',to_date('15-10-13','DD-MM-RR'),'PROVISIONING',to_date('15-10-13','DD-MM-RR'),20131015153706,20131015153706);
REM INSERTING into SCHEMA_MIGRATIONS
SET DEFINE OFF;
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130802050336');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812073441');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812074444');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812074529');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812074548');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812093327');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812112259');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812121147');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812125050');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130812153946');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130813075031');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130816100409');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130820055034');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130822115547');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130823035745');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130823062344');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130823072013');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130823150602');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130824054424');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130824111336');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130824122856');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130826084406');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130826110255');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130827055210');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130830092344');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130904064124');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130904091440');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130904125214');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130904125315');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130905095041');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130911082052');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130911094048');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130911095208');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130911111134');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130912130213');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130916070848');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130924105217');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20130926061543');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20131003070050');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20131003070651');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20131004110241');
Insert into SCHEMA_MIGRATIONS (VERSION) values ('20131009054038');
--------------------------------------------------------
--  DDL for Index PK_PROVIDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROVIDERS" ON "PROVIDERS" ("SYS_PROVIDER_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_AUDIT_TRAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_AUDIT_TRAILS" ON "AUDIT_TRAILS" ("SYS_AUDIT_TRAIL_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_APP_UPLOAD_FIELDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APP_UPLOAD_FIELDS" ON "APP_UPLOAD_FIELDS" ("SYS_APP_UPLOAD_FIELD_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_APP_FIELD_VALIDATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APP_FIELD_VALIDATIONS" ON "APP_UPLOAD_FIELD_VALIDATIONS" ("SYS_APP_FIELD_VALIDATION_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_REGISTERED_APPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_REGISTERED_APPS" ON "REGISTERED_APPS" ("REGISTERED_APP_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UNIQUE_SCHEMA_MIGRATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIQUE_SCHEMA_MIGRATIONS" ON "SCHEMA_MIGRATIONS" ("VERSION") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_ORGANIZATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ORGANIZATIONS" ON "ORGANIZATIONS" ("SYS_ORGANIZATION_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_ROLES" ON "ROLES" ("ROLE_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_PROVIDER_DEA_NUMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROVIDER_DEA_NUMBERS" ON "PROVIDER_DEA_NUMBERS" ("SYS_PROVIDER_DEA_NUMBER_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_ORGANIZATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_ORGANIZATIONS" ON "ORGANIZATIONS" ("ORGANIZATION_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_OIS_BATCH_UPLOADS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_OIS_BATCH_UPLOADS" ON "OIS_BATCH_UPLOADS" ("OIS_BATCH_UPLOAD_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_PROVIDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_PROVIDERS" ON "PROVIDERS" ("PROVIDER_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_PROFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_PROFILES" ON "PROFILES" ("PROFILE_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_REGISTERED_APPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_REGISTERED_APPS" ON "REGISTERED_APPS" ("SYS_REGISTERED_APP_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_PROFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROFILES" ON "PROFILES" ("SYS_PROFILE_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_APP_FIELD_VALIDATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_APP_FIELD_VALIDATIONS" ON "APP_UPLOAD_FIELD_VALIDATIONS" ("APP_FIELD_VALIDATION_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_OIS_BATCH_UPLOADS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_OIS_BATCH_UPLOADS" ON "OIS_BATCH_UPLOADS" ("SYS_OIS_BATCH_UPLOAD_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_PROVIDER_APP_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_PROVIDER_APP_DETAILS" ON "PROVIDER_APP_DETAILS" ("PROVIDER_APP_DETAIL_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_AUDIT_TRAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_AUDIT_TRAILS" ON "AUDIT_TRAILS" ("AUDIT_TRAIL_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_CAOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_CAOS" ON "CAOS" ("CAO_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index I_CAOS_RESET_PASSWORD_TOKEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "I_CAOS_RESET_PASSWORD_TOKEN" ON "CAOS" ("RESET_PASSWORD_TOKEN") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_PROVIDER_ERROR_LOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROVIDER_ERROR_LOGS" ON "PROVIDER_ERROR_LOGS" ("SYS_PROVIDER_ERROR_LOG_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_APP_UPLOAD_FIELDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_APP_UPLOAD_FIELDS" ON "APP_UPLOAD_FIELDS" ("APP_UPLOAD_FIELD_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_COAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COAS" ON "CAOS" ("SYS_CAO_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index INDEX_CAOS_ON_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDEX_CAOS_ON_EMAIL" ON "CAOS" ("EMAIL") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_PROVIDER_DEA_NUMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_PROVIDER_DEA_NUMBERS" ON "PROVIDER_DEA_NUMBERS" ("PROVIDER_DEA_NUMBER_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_PROVIDER_APP_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROVIDER_APP_DETAILS" ON "PROVIDER_APP_DETAILS" ("SYS_PROVIDER_APP_DETAIL_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index UQ_PROVIDER_ERROR_LOGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_PROVIDER_ERROR_LOGS" ON "PROVIDER_ERROR_LOGS" ("PROVIDER_ERROR_LOG_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  DDL for Index PK_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ROLES" ON "ROLES" ("SYS_ROLE_ID") TABLESPACE TS_NDX
/
--------------------------------------------------------
--  Constraints for Table PROVIDERS
--------------------------------------------------------

  ALTER TABLE "PROVIDERS" ADD CONSTRAINT "UQ_PROVIDERS" UNIQUE ("PROVIDER_ID") ENABLE
  ALTER TABLE "PROVIDERS" ADD CONSTRAINT "PK_PROVIDERS" PRIMARY KEY ("SYS_PROVIDER_ID") ENABLE
  ALTER TABLE "PROVIDERS" MODIFY ("PROVIDER_ID" NOT NULL ENABLE)
  ALTER TABLE "PROVIDERS" MODIFY ("SYS_PROVIDER_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table APP_UPLOAD_FIELDS
--------------------------------------------------------

  ALTER TABLE "APP_UPLOAD_FIELDS" ADD CONSTRAINT "UQ_APP_UPLOAD_FIELDS" UNIQUE ("APP_UPLOAD_FIELD_ID") ENABLE
  ALTER TABLE "APP_UPLOAD_FIELDS" ADD CONSTRAINT "PK_APP_UPLOAD_FIELDS" PRIMARY KEY ("SYS_APP_UPLOAD_FIELD_ID") ENABLE
  ALTER TABLE "APP_UPLOAD_FIELDS" MODIFY ("APP_UPLOAD_FIELD_ID" NOT NULL ENABLE)
  ALTER TABLE "APP_UPLOAD_FIELDS" MODIFY ("SYS_APP_UPLOAD_FIELD_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table REGISTERED_APPS
--------------------------------------------------------

  ALTER TABLE "REGISTERED_APPS" ADD CONSTRAINT "UQ_REGISTERED_APPS" UNIQUE ("REGISTERED_APP_ID") ENABLE
  ALTER TABLE "REGISTERED_APPS" ADD CONSTRAINT "PK_REGISTERED_APPS" PRIMARY KEY ("SYS_REGISTERED_APP_ID") ENABLE
  ALTER TABLE "REGISTERED_APPS" MODIFY ("REGISTERED_APP_ID" NOT NULL ENABLE)
  ALTER TABLE "REGISTERED_APPS" MODIFY ("SYS_REGISTERED_APP_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table PROVIDER_APP_DETAILS
--------------------------------------------------------

  ALTER TABLE "PROVIDER_APP_DETAILS" ADD CONSTRAINT "UQ_PROVIDER_APP_DETAILS" UNIQUE ("PROVIDER_APP_DETAIL_ID") ENABLE
  ALTER TABLE "PROVIDER_APP_DETAILS" ADD CONSTRAINT "PK_PROVIDER_APP_DETAILS" PRIMARY KEY ("SYS_PROVIDER_APP_DETAIL_ID") ENABLE
  ALTER TABLE "PROVIDER_APP_DETAILS" MODIFY ("PROVIDER_APP_DETAIL_ID" NOT NULL ENABLE)
  ALTER TABLE "PROVIDER_APP_DETAILS" MODIFY ("SYS_PROVIDER_APP_DETAIL_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table PROVIDER_DEA_NUMBERS
--------------------------------------------------------

  ALTER TABLE "PROVIDER_DEA_NUMBERS" ADD CONSTRAINT "UQ_PROVIDER_DEA_NUMBERS" UNIQUE ("PROVIDER_DEA_NUMBER_ID") ENABLE
  ALTER TABLE "PROVIDER_DEA_NUMBERS" ADD CONSTRAINT "PK_PROVIDER_DEA_NUMBERS" PRIMARY KEY ("SYS_PROVIDER_DEA_NUMBER_ID") ENABLE
  ALTER TABLE "PROVIDER_DEA_NUMBERS" MODIFY ("PROVIDER_DEA_NUMBER_ID" NOT NULL ENABLE)
  ALTER TABLE "PROVIDER_DEA_NUMBERS" MODIFY ("SYS_PROVIDER_DEA_NUMBER_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table APP_UPLOAD_FIELD_VALIDATIONS
--------------------------------------------------------

  ALTER TABLE "APP_UPLOAD_FIELD_VALIDATIONS" ADD CONSTRAINT "UQ_APP_FIELD_VALIDATIONS" UNIQUE ("APP_FIELD_VALIDATION_ID") ENABLE
  ALTER TABLE "APP_UPLOAD_FIELD_VALIDATIONS" ADD CONSTRAINT "PK_APP_FIELD_VALIDATIONS" PRIMARY KEY ("SYS_APP_FIELD_VALIDATION_ID") ENABLE
  ALTER TABLE "APP_UPLOAD_FIELD_VALIDATIONS" MODIFY ("APP_FIELD_VALIDATION_ID" NOT NULL ENABLE)
  ALTER TABLE "APP_UPLOAD_FIELD_VALIDATIONS" MODIFY ("SYS_APP_FIELD_VALIDATION_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table PROFILES
--------------------------------------------------------

  ALTER TABLE "PROFILES" ADD CONSTRAINT "UQ_PROFILES" UNIQUE ("PROFILE_ID") ENABLE
  ALTER TABLE "PROFILES" ADD CONSTRAINT "PK_PROFILES" PRIMARY KEY ("SYS_PROFILE_ID") ENABLE
  ALTER TABLE "PROFILES" MODIFY ("PROFILE_ID" NOT NULL ENABLE)
  ALTER TABLE "PROFILES" MODIFY ("SYS_PROFILE_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table SCHEMA_MIGRATIONS
--------------------------------------------------------

  ALTER TABLE "SCHEMA_MIGRATIONS" MODIFY ("VERSION" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table OIS_BATCH_UPLOADS
--------------------------------------------------------

  ALTER TABLE "OIS_BATCH_UPLOADS" ADD CONSTRAINT "UQ_OIS_BATCH_UPLOADS" UNIQUE ("OIS_BATCH_UPLOAD_ID") ENABLE
  ALTER TABLE "OIS_BATCH_UPLOADS" ADD CONSTRAINT "PK_OIS_BATCH_UPLOADS" PRIMARY KEY ("SYS_OIS_BATCH_UPLOAD_ID") ENABLE
  ALTER TABLE "OIS_BATCH_UPLOADS" MODIFY ("OIS_BATCH_UPLOAD_ID" NOT NULL ENABLE)
  ALTER TABLE "OIS_BATCH_UPLOADS" MODIFY ("SYS_OIS_BATCH_UPLOAD_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table AUDIT_TRAILS
--------------------------------------------------------

  ALTER TABLE "AUDIT_TRAILS" ADD CONSTRAINT "UQ_AUDIT_TRAILS" UNIQUE ("AUDIT_TRAIL_ID") ENABLE
  ALTER TABLE "AUDIT_TRAILS" ADD CONSTRAINT "PK_AUDIT_TRAILS" PRIMARY KEY ("SYS_AUDIT_TRAIL_ID") ENABLE
  ALTER TABLE "AUDIT_TRAILS" MODIFY ("AUDIT_TRAIL_ID" NOT NULL ENABLE)
  ALTER TABLE "AUDIT_TRAILS" MODIFY ("SYS_AUDIT_TRAIL_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table ORGANIZATIONS
--------------------------------------------------------

  ALTER TABLE "ORGANIZATIONS" ADD CONSTRAINT "UQ_ORGANIZATIONS" UNIQUE ("ORGANIZATION_ID") ENABLE
  ALTER TABLE "ORGANIZATIONS" ADD CONSTRAINT "PK_ORGANIZATIONS" PRIMARY KEY ("SYS_ORGANIZATION_ID") ENABLE
  ALTER TABLE "ORGANIZATIONS" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE)
  ALTER TABLE "ORGANIZATIONS" MODIFY ("SYS_ORGANIZATION_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table CAOS
--------------------------------------------------------

  ALTER TABLE "CAOS" ADD CONSTRAINT "UQ_CAOS" UNIQUE ("CAO_ID") ENABLE
  ALTER TABLE "CAOS" ADD CONSTRAINT "PK_COAS" PRIMARY KEY ("SYS_CAO_ID") ENABLE
  ALTER TABLE "CAOS" MODIFY ("ENCRYPTED_PASSWORD" NOT NULL ENABLE)
  ALTER TABLE "CAOS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "CAOS" MODIFY ("CAO_ID" NOT NULL ENABLE)
  ALTER TABLE "CAOS" MODIFY ("SYS_CAO_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE)
  ALTER TABLE "ROLES" MODIFY ("SYS_ROLE_ID" NOT NULL ENABLE)
  ALTER TABLE "ROLES" ADD CONSTRAINT "UQ_ROLES" UNIQUE ("ROLE_ID") ENABLE
  ALTER TABLE "ROLES" ADD CONSTRAINT "PK_ROLES" PRIMARY KEY ("SYS_ROLE_ID") ENABLE
/
--------------------------------------------------------
--  Constraints for Table PROVIDER_ERROR_LOGS
--------------------------------------------------------

  ALTER TABLE "PROVIDER_ERROR_LOGS" ADD CONSTRAINT "UQ_PROVIDER_ERROR_LOGS" UNIQUE ("PROVIDER_ERROR_LOG_ID") ENABLE
  ALTER TABLE "PROVIDER_ERROR_LOGS" ADD CONSTRAINT "PK_PROVIDER_ERROR_LOGS" PRIMARY KEY ("SYS_PROVIDER_ERROR_LOG_ID") ENABLE
  ALTER TABLE "PROVIDER_ERROR_LOGS" MODIFY ("PROVIDER_ERROR_LOG_ID" NOT NULL ENABLE)
  ALTER TABLE "PROVIDER_ERROR_LOGS" MODIFY ("SYS_PROVIDER_ERROR_LOG_ID" NOT NULL ENABLE)
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_APP_FIELD_VALIDATIONS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_APP_FIELD_VALIDATIONS" BEFORE INSERT OR UPDATE
ON SPARKWAY.APP_UPLOAD_FIELD_VALIDATIONS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.APP_FIELD_VALIDATION_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.APP_FIELD_VALIDATION_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_APP_FIELD_VALIDATIONS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_APP_UPLOAD_FIELDS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_APP_UPLOAD_FIELDS" BEFORE INSERT OR UPDATE
ON SPARKWAY.APP_UPLOAD_FIELDS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.APP_UPLOAD_FIELD_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.APP_UPLOAD_FIELD_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_APP_UPLOAD_FIELDS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_AUDIT_TRAILS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_AUDIT_TRAILS" BEFORE INSERT OR UPDATE
ON SPARKWAY.AUDIT_TRAILS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.AUDIT_TRAIL_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.AUDIT_TRAIL_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_AUDIT_TRAILS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_CAOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_CAOS" BEFORE INSERT OR UPDATE
ON SPARKWAY.CAOS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.cao_id IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.cao_id FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_CAOS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_OIS_BATCH_UPLOADS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_OIS_BATCH_UPLOADS" BEFORE INSERT OR UPDATE
ON SPARKWAY.OIS_BATCH_UPLOADS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.OIS_BATCH_UPLOAD_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.OIS_BATCH_UPLOAD_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_OIS_BATCH_UPLOADS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_ORGANIZATIONS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_ORGANIZATIONS" BEFORE INSERT OR UPDATE
ON SPARKWAY.ORGANIZATIONS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.ORGANIZATION_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.ORGANIZATION_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_ORGANIZATIONS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_PROFILES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_PROFILES" BEFORE INSERT OR UPDATE
ON SPARKWAY.PROFILES FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PROFILE_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PROFILE_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_PROFILES" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_PROVIDERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_PROVIDERS" BEFORE INSERT OR UPDATE
ON SPARKWAY.PROVIDERS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PROVIDER_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PROVIDER_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_PROVIDERS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_PROVIDER_APP_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_PROVIDER_APP_DETAILS" BEFORE INSERT OR UPDATE
ON SPARKWAY.PROVIDER_APP_DETAILS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PROVIDER_APP_DETAIL_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PROVIDER_APP_DETAIL_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_PROVIDER_APP_DETAILS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_PROVIDER_DEA_NUMBERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_PROVIDER_DEA_NUMBERS" BEFORE INSERT OR UPDATE
ON SPARKWAY.PROVIDER_DEA_NUMBERS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PROVIDER_DEA_NUMBER_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PROVIDER_DEA_NUMBER_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_PROVIDER_DEA_NUMBERS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_PROVIDER_ERROR_LOGS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_PROVIDER_ERROR_LOGS" BEFORE INSERT OR UPDATE
ON SPARKWAY.PROVIDER_ERROR_LOGS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PROVIDER_ERROR_LOG_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PROVIDER_ERROR_LOG_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_PROVIDER_ERROR_LOGS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_REGISTERED_APPS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_REGISTERED_APPS" BEFORE INSERT OR UPDATE
ON SPARKWAY.REGISTERED_APPS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.REGISTERED_APP_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.REGISTERED_APP_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_REGISTERED_APPS" ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TRI_BIU_ROLES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRI_BIU_ROLES" BEFORE INSERT OR UPDATE
ON SPARKWAY.ROLES FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.ROLE_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.ROLE_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
ALTER TRIGGER "TRI_BIU_ROLES" ENABLE
/

--------------------------------------------------------
--   EPCS: Added new Biometric FQDN field in PROVIDER table
--------------------------------------------------------
ALTER TABLE SPARKWAY.PROVIDERS ADD (fqdn VARCHAR2(255));
/

--------------------------------------------------------
--   EPCS: Added GENDER, SOCIAL_SECURITY_NUMBER in Providers Table
--------------------------------------------------------


ALTER TABLE SPARKWAY.PROVIDERS ADD (
GENDER VARCHAR2(1 CHAR),
SOCIAL_SECURITY_NUMBER VARCHAR2(255 CHAR));
/

--------------------------------------------------------
--  DDL for Table PERFORMANCE_LOGS
--------------------------------------------------------
CREATE TABLE "PERFORMANCE_LOGS" (
"SYS_PERFORMANCE_LOG_ID" VARCHAR2(50 CHAR) NOT NULL,
"PERFORMANCE_LOG_ID" VARCHAR2(50 CHAR),
"CONTROLLER_NAME" VARCHAR2(255),
"SERVER_NAME" VARCHAR2(50),
"SERVER_VERSION" VARCHAR2(50),
"SERVER_IP" VARCHAR2(50),
"SERVER_INSTANCE_NAME" VARCHAR2(255),
"ACTION_NAME" VARCHAR2(255),
"CLIENT_ID" VARCHAR2(36),
"REQUEST_PARAMS" CLOB,
"REQUEST_IP" VARCHAR2(20),
"REQUEST_CONTENT" VARCHAR2(255),
"REQUEST_TIME" TIMESTAMP(6),
"RESPONSE_CONTENT" CLOB,
"RESPONSE_TIME" NUMBER,
"CLIENT_PLATFORM" VARCHAR2(50),
"CLIENT_VERSION" VARCHAR2(50),
"ERROR_CODE" VARCHAR2(255),
"ERROR_DESCRIPTION" CLOB,
"DB_RESPONSE_TIME" NUMBER,
"TOTAL_RESPONSE_TIME" NUMBER,
"DELETED"  VARCHAR2(1 BYTE)    DEFAULT 'n',
"CREATORID" VARCHAR2(30 BYTE),
"CREATEDDATE" DATE,
"LASTUPDATEID" VARCHAR2(30 BYTE),
"LASTUPDATEDATE" DATE,
"CREATEDDATE_AS_NUMBER" NUMBER(18),
"LASTUPDATEDATE_AS_NUMBER" NUMBER(18)
);
/
--------------------------------------------------------
--  DDL for Trigger PERFORMANCE_LOGS
--------------------------------------------------------

CREATE OR REPLACE TRIGGER SPARKWAY.TRI_BIU_PERFORMANCE_LOGS BEFORE INSERT OR UPDATE
ON SPARKWAY.PERFORMANCE_LOGS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.PERFORMANCE_LOG_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.PERFORMANCE_LOG_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
/

--------------------------------------------------------
--  Constraints for Table PERFORMANCE_LOGS
--------------------------------------------------------
ALTER TABLE PERFORMANCE_LOGS ADD CONSTRAINT "PK_PERFORMANCE_LOGS" PRIMARY KEY ("SYS_PERFORMANCE_LOG_ID") ENABLE;
ALTER TABLE PERFORMANCE_LOGS ADD CONSTRAINT "UQ_PERFORMANCE_LOGS" UNIQUE ("PERFORMANCE_LOG_ID") ENABLE;
/

--------------------------------------------------------
--  DDL for Sequence PERFORMANCE_LOGS
--------------------------------------------------------

CREATE SEQUENCE  "PERFORMANCE_LOGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

-----------------------------------------------------------
--   Rcopia: Added fields as per the Rcopia csv template in PROVIDER table
-----------------------------------------------------------
ALTER TABLE SPARKWAY.PROVIDERS ADD (
USE_EXISTING_ACCOUNT VARCHAR2(1),
MEMBER_TYPE VARCHAR2(255 CHAR),
PRACTICE_GROUP VARCHAR2(255 CHAR),
MEDICAL_LICENSE_NUMBER VARCHAR2(255 CHAR),
MEDICAL_LICENSE_STATE VARCHAR2(255 CHAR),
SPECIALTY VARCHAR2(255 CHAR),
SECONDARY_LICENSE VARCHAR2(255 CHAR),
EXTERNAL_ID_1 VARCHAR2(255 CHAR),
EXTERNAL_ID_2 VARCHAR2(255 CHAR));
/

-----------------------------------------------------------
--   Moxy: Added fields as per the MOXY csv template in PROVIDER table
-----------------------------------------------------------
ALTER TABLE SPARKWAY.PROVIDERS ADD (
DISPLAY_NAME VARCHAR2(255 CHAR),
USER_TYPE VARCHAR2(255 CHAR),
RESIDENT VARCHAR2(1),
SECURITY_QUESTION VARCHAR2(255 CHAR),
SECURITY_ANSWER VARCHAR2(255 CHAR),
PHONE_EXTENSION VARCHAR2(255 CHAR),
FAX_EXTENSION VARCHAR2(255 CHAR),
COUNTRY VARCHAR2(255 CHAR),
OFFICE_ADDRESS_LINE_1 CLOB,
OFFICE_ADDRESS_LINE_2 CLOB,
OFFICE_ADDRESS_CITY VARCHAR2(255 CHAR),
OFFICE_ADDRESS_STATE VARCHAR2(255 CHAR),
OFFICE_ADDRESS_COUNTRY VARCHAR2(255 CHAR),
OFFICE_ADDRESS_ZIP VARCHAR2(255 CHAR));
/


---------------------------------------------------------------------------------------------------
-- DLL for Adding field in RegisteredApp table for mapping Onestop Router ois_name with RegisteredApp's app_name
---------------------------------------------------------------------------------------------------
ALTER TABLE "REGISTERED_APPS" ADD (
DISPLAY_NAME VARCHAR2(255 CHAR));
/


--------------------------------------------------------
--  DDL for Table OLD_PASSWORDS
--------------------------------------------------------
CREATE TABLE "OLD_PASSWORDS" (
"SYS_OLD_PASSWORD_ID" VARCHAR2(50 CHAR) NOT NULL,
"OLD_PASSWORD_ID" VARCHAR2(50 CHAR),
"ENCRYPTED_PASSWORD" VARCHAR2(255 CHAR) NOT NULL,
"PASSWORD_SALT" VARCHAR2(255 CHAR),
"PASSWORD_ARCHIVABLE_TYPE" VARCHAR2(255 CHAR) NOT NULL,
"PASSWORD_ARCHIVABLE_ID" VARCHAR2(255 CHAR) NOT NULL,
"DELETED"  VARCHAR2(1 BYTE)    DEFAULT 'n',
"CREATORID" VARCHAR2(30 BYTE),
"CREATEDDATE" DATE,
"LASTUPDATEID" VARCHAR2(30 BYTE),
"LASTUPDATEDATE" DATE,
"CREATEDDATE_AS_NUMBER" NUMBER(18),
"LASTUPDATEDATE_AS_NUMBER" NUMBER(18)
);
/
--------------------------------------------------------
--  DDL for Trigger OLD_PASSWORDS
--------------------------------------------------------

CREATE OR REPLACE TRIGGER dev_ois.OLD_PASSWORDS BEFORE INSERT OR UPDATE
ON dev_ois.OLD_PASSWORDS FOR EACH ROW
BEGIN
IF INSERTING
THEN
  IF (:NEW.OLD_PASSWORD_ID IS NULL)
      THEN
         SELECT SYS_GUID() INTO :NEW.OLD_PASSWORD_ID FROM DUAL;
  END IF;  
  :NEW.CREATEDDATE := SYSDATE;
  :NEW.CREATORID := USER;
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.CREATEDDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.CREATEDDATE, 'YYYYMMDDHH24MISS'));
  :NEW.LASTUPDATEDATE_AS_NUMBER := TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
ELSIF UPDATING
THEN
  :NEW.LASTUPDATEDATE := SYSDATE;
  :NEW.LASTUPDATEID := USER;
  :NEW.LASTUPDATEDATE_AS_NUMBER :=
   TO_NUMBER (TO_CHAR (:NEW.LASTUPDATEDATE, 'YYYYMMDDHH24MISS'));
END IF;
END;
/

--------------------------------------------------------
--  Constraints for Table OLD_PASSWORDS
--------------------------------------------------------
ALTER TABLE OLD_PASSWORDS ADD CONSTRAINT "PK_OLD_PASSWORDS" PRIMARY KEY ("SYS_OLD_PASSWORD_ID") ENABLE;
ALTER TABLE OLD_PASSWORDS ADD CONSTRAINT "UQ_OLD_PASSWORDS" UNIQUE ("OLD_PASSWORD_ID") ENABLE;
/

--------------------------------------------------------
--  DDL for Sequence OLD_PASSWORDS
--------------------------------------------------------

CREATE SEQUENCE  "OLD_PASSWORDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

--------------------------------------------------------
--  INDEX for OLD_PASSWORDS
--------------------------------------------------------

CREATE INDEX INDEX_PASSWORD_ARCHIVABLE ON OLD_PASSWORDS(PASSWORD_ARCHIVABLE_TYPE, PASSWORD_ARCHIVABLE_ID);

-----------------------------------------------------------
--   Rcopia: Added fields as per the new [ MOXY-13333 ] Rcopia csv template in PROVIDER table
-----------------------------------------------------------

ALTER TABLE SPARKWAY.PROVIDERS ADD (
PRACTICE_EXTERNAL_ID VARCHAR2(255),
DEFAULT_LOCATION_EXTERNAL_ID VARCHAR2(255));
/

-----------------------------------------------------------
--   Provisioning: Added fields as per the ticket [ MOXY-13707 ] - OIS_SUBSCRIBED, VENDOR_NAME and VENDOR_PASSWORD 
-----------------------------------------------------------

ALTER TABLE SPARKWAY.CAOS ADD (
RCOPIA_OIS_SUBSCRIBED NUMBER(1,0),
EPCS_OIS_SUBSCRIBED NUMBER(1,0),
RCOPIA_VENDOR_NAME VARCHAR2(255),
RCOPIA_VENDOR_PASSWORD VARCHAR2(255),
EPCS_VENDOR_NAME VARCHAR2(255),
EPCS_VENDOR_PASSWORD VARCHAR2(255));
/

-----------------------------------------------------------
--   Provisioning: Added fields as per the ticket [ MOXY-13747 - There should be some Security Q/A in order to reset a Password ] - SECURITY_QUESTION_ID, SECURITY_ANSWER 
-----------------------------------------------------------

ALTER TABLE SPARKWAY.CAOS ADD (
SECURITY_QUESTION VARCHAR2(255),
SECURITY_ANSWER VARCHAR2(255));
/