development:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: development
  password: password

test: &test
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: test
  password: test

production:
  adapter: oracle_enhanced
  host: 172.16.10.103
  port: 1521
  database: DV1OIS
  username: drfirst
  password: drfirst123

cucumber:
  <<: *test

performance:
  <<: *test
