Given /the following (.*) exists:/ do |model, table|
  created_model = create(model.parameterize('_').to_sym, table.rows_hash)

  # Re-set autogenerated attributes if provided in the table
  auto_generated_attributes = ['client_password', 'ois_password', 'token', 'created_date']
  auto_generated_attributes.each do |attribute|
    created_model.send(:"#{attribute}=", table.rows_hash[attribute]) if table.rows_hash[attribute].present?
  end
  created_model.save!
end
