#Configuration for the different environments

defaults: &defaults

development:
    cache_server: 'localhost:6379'

test:
    cache_server: '' # Need to enter

staging:
    cache_server: '' # Need to enter

production:
    cache_server: '' # Need to enter
